---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Role: Analysis
hostnames:
  - tag:Name
keyed_groups:
  - key: tags.Role
    separator: ''
compose:
  ansible_host: public_ip_address
  ansible_user: "'ec2-user'"
